projectit/Controllers/PostItController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using projectit.DAO;
using projectit.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Data.SqlClient;

namespace projectit.Controllers
{
    public class PostItController : DefaultController<PostItViewModel>
    {
        public PostItController()
        {
            DAO = new PostItDAO();
        }

        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (MemoryStream ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }


        protected override void ValidateData(PostItViewModel model, string Operation)
        {
            base.ValidateData(model, Operation);

            if (string.IsNullOrEmpty(model.header))
                ModelState.AddModelError("header", "Preencha o título da ação.");

            if (string.IsNullOrEmpty(model.doing_by) && model.status != "Stories")
                ModelState.AddModelError("doing_by", "Preencha o responsável.");

            if (string.IsNullOrEmpty(model.body))
                ModelState.AddModelError("body", "Preencha a descrição da ação.");

            if (string.IsNullOrEmpty(model.status))
                ModelState.AddModelError("status", "Determine o status da ação.");

            if (Operation != "A")
                if (model.project_id <= 0)
                ModelState.AddModelError("project_id", "Determine um projeto");

        }
    }
}

projectit/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using projectit.DAO;
using projectit.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Data.SqlClient;

namespace projectit.Controllers
{
    public class ProjectController : DefaultController<ProjectViewModel>
    {
        public ProjectController()
        {
            DAO = new ProjectDAO();
        }

        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (MemoryStream ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }

        protected override void ValidateData(ProjectViewModel model, string Operation)
        {
            base.ValidateData(model, Operation);

            if (string.IsNullOrEmpty(model.description))
                ModelState.AddModelError("description", "Preencha a descrição.");

            if (model.code is null)
                ModelState.AddModelError("code", "Campo Obrigatório.");

            if (model.picture != null && model.picture.Length / 1024 / 1024 >= 2)
                ModelState.AddModelError("Imagem", "Imagem limitada à 2MB.");

            if (model.team_id <= 0)
                ModelState.AddModelError("team_id", "Determine o time responsável pelo projeto");

            if (ModelState.IsValid)
            {
                if (Operation == "A" && model.picture == null)
                {
                    ProjectViewModel gam = DAO.Query(model.id);
                    model.Byte_picture = gam.Byte_picture;
                }
                else
                {
                    model.Byte_picture = ConvertImageToByte(model.picture);
                }
            }

        }
    }
}

projectit/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using projectit.DAO;
using projectit.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Data.SqlClient;

namespace projectit.Controllers
{
    public class TeamController : DefaultController<TeamViewModel>
    {
        public TeamController()
        {
            DAO = new TeamDAO();
        }

        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (MemoryStream ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }


        protected override void ValidateData(TeamViewModel model, string Operation)
        {
            base.ValidateData(model, Operation);

            if (string.IsNullOrEmpty(model.name))
                ModelState.AddModelError("name", "Preencha o seu nome.");

            if (string.IsNullOrEmpty(model.skill))
                ModelState.AddModelError("skill", "Preencha a habilidade principal da equipe.");

            if (model.picture != null && model.picture.Length / 1024 / 1024 >= 5)
                ModelState.AddModelError("picture", "Imagem limitada à 5MB.");

            if (model.user_id <= 0)
                ModelState.AddModelError("user_id", "Selecione os membros do time");

            if (ModelState.IsValid)
            {
                if (Operation == "A" && model.picture == null)
                {
                    TeamViewModel picture = DAO.Query(model.id);
                    model.Byte_picture = picture.Byte_picture;
                }
                else
                {
                    model.Byte_picture = ConvertImageToByte(model.picture);
                }
            }
        }

        
    }
}

projectit/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using projectit.DAO;
using projectit.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc.Filters;

namespace projectit.Controllers
{
    public class UsersController : DefaultController<UsersViewModel>
    {
        public UsersController()
        {
            DAO = new UsersDAO();
        }

        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (MemoryStream ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }


        protected override void ValidateData(UsersViewModel model, string Operation)
        {
            base.ValidateData(model, Operation);

            if (string.IsNullOrEmpty(model.name))
                ModelState.AddModelError("name", "Preencha o o seu nome.");

            if (string.IsNullOrEmpty(model.nickname))
                ModelState.AddModelError("nickname", "Preencha o nickname.");

            if (string.IsNullOrEmpty(model.email))
                ModelState.AddModelError("email", "Preencha o email.");

            if (string.IsNullOrEmpty(model.password))
                ModelState.AddModelError("password", "Preencha a senha");

            //if (string.IsNullOrEmpty(model.confirm_password) || model.confirm_password == model.password)
            //    ModelState.AddModelError("confirm_password", "Confirme a senha");
            

            if (model.picture != null && model.picture.Length / 1024 / 1024 >= 5)
                ModelState.AddModelError("picture", "Imagem limitada à 5MB.");

            if (ModelState.IsValid)
            {
                if (Operation == "A" && model.picture == null)
                {
                    UsersViewModel picture = DAO.Query(model.id);
                    model.Byte_picture = picture.Byte_picture;
                }
                else
                {
                    model.Byte_picture = ConvertImageToByte(model.picture);
                }
            }
        }

        public override IActionResult Index()
        {
            if (!HelperController.CheckLogin(HttpContext.Session))
            {
                ViewBag.Operacao = "I";
                UsersViewModel model = new UsersViewModel();
                return View("Form", model);
            }
            else
            {
                var list = DAO.List();
                return View(list);
            }

        }
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (HelperController.CheckLogin(HttpContext.Session))
            {
                ViewBag.Login = true;
                base.OnActionExecuting(context);
            }
        }


    }
}

projectit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
</head>
<body>
    @*<nav class="navbar navbar-fixed-top navbar-inverse">
            <div class="container navbar_container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Project It</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        @if (ViewBag.Login == true)
                        {
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                            <li><a asp-area="" asp-controller="Team" asp-action="Index">Team</a></li>
                            <li><a asp-area="" asp-controller="Project" asp-action="Index">Project</a></li>
                            <li><a asp-area="" asp-controller="PostIt" asp-action="Index">PostIt</a></li>
                            <li><a asp-area="" asp-controller="Login" asp-action="LogOff">Sair</a></li>

                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Login" asp-action="Register">Registrar</a></li>
                            <li><a asp-area="" asp-controller="Login" asp-action="Index">Entrar</a></li>
                        }

                    </ul>

                </div>
            </div>
        </nav>*@

    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Project It</a>
                <img src="https://midiatividades.files.wordpress.com/2012/10/post-it-note-with-push-pin.png" height="40"/>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    @if (ViewBag.Login == true)
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                        <li><a asp-area="" asp-controller="Team" asp-action="Index">Team</a></li>
                        <li><a asp-area="" asp-controller="Project" asp-action="Index">Project</a></li>
                        <li><a asp-area="" asp-controller="PostIt" asp-action="Index">PostIt</a></li>
                        <li><a asp-area="" asp-controller="Login" asp-action="LogOff">Sair</a></li>

                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                        <li><a asp-area="" asp-controller="Login" asp-action="Register">Registrar</a></li>
                        <li><a asp-area="" asp-controller="Login" asp-action="Index">Entrar</a></li>
                    }

                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content" id="body">
        @RenderBody()
    </div>

    <footer class="footer navbar-fixed-bottom">
        <hr />
        <p>&copy; 2020 - ProjectIt</p>
    </footer>




    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>